In [4]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [3]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Using cached scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [scikit-learn][0m [scikit-learn]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install pandas
pip install matplotlib
pip install seaborn
pip install tensorflow
pip install keras

SyntaxError: invalid syntax (91357028.py, line 1)

In [6]:
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install tensorflow
!pip install keras

Collecting pandas
  Using cached pandas-3.0.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Collecting matplotlib
  Using cached matplotlib-3.11.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.64.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (123 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.3.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.11.1-cp311-cp311-macosx_11_0_arm64.whl (9.3 MB)
Using cached contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (270 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.64.0-cp311-cp311-macosx_10_9_universal2.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 192.8 kB/s  0:00:17 eta 0:00:02
Downloading kiwisolver-1.5.1-cp311-cp311-macosx_11_0_arm64.whl (64 kB)
Using cached pillow-12.3.0-cp311-cp311-macosx_11_0_arm64.whl (4.8 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.64.0 kiwisolver-1.5.1 matplotlib-3.11.1 pillow-12.3.0 pyparsing-3.3.2
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Requirement already satisfied: tensorflow in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (7.36.1)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (83.0.0)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (1.83.1)
Requirement already satisfied: keras>=3.12.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (2.4.6)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Requirement already satisfied: keras in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (3.15.1)
Requirement already satisfied: absl-py in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (2.5.0)
Requirement already satisfied: numpy in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (2.4.6)
Requirement already satisfied: rich in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (15.0.0)
Requirement already satisfied: namex in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (3.14.0)
Requirement already satisfied: optree in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (0.20.0)
Requirement already satisfied: ml-dtypes in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (0.6.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from keras) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from optree->keras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from rich->keras) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/dl/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

print(tf.__version__)

2.21.0

In [4]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [9]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [5]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [6]:

X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [7]:

X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42, stratify=y)

In [11]:

model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [13]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [16]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 1 , verbose = 1
)

Epoch 1/100

ValueError: Cannot take the length of shape with unknown rank.

In [17]:
X_train_np = np.asarray(X_train).astype("float32")
X_test_np = np.asarray(X_test).astype("float32")

y_train_np = np.asarray(y_train).astype("float32")
y_test_np = np.asarray(y_test).astype("float32")

In [18]:
history = model.fit(
    X_train_np,
    y_train_np,
    validation_data=(X_test_np, y_test_np),
    epochs=100,
    batch_size=1,
    verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.6436 - val_accuracy: 0.7500 - val_loss: 0.6656
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.6373 - val_accuracy: 1.0000 - val_loss: 0.6619
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6342 - val_accuracy: 1.0000 - val_loss: 0.6600
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6337 - val_accuracy: 1.0000 - val_loss: 0.6571
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6307 - val_accuracy: 1.0000 - val_loss: 0.6553
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6291 - val_accuracy: 1.0000 - val_loss: 0.6539
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6281 - val_accuracy: 1.0000 - val_loss: 0.6521
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6261 - val_accuracy: 1.0000 - val_loss: 0.6507
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6249 - val_accuracy: 1.0000 - val_loss: 0.6490
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6238 - val_accuracy: 1.0000 - val_loss: 0.6478
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6225 - val_accuracy: 1.0000 - val_loss: 0.6466
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6215 - val_accuracy: 1.0000 - val_loss: 0.6458
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6199 - val_accuracy: 1.0000 - val_loss: 0.6445
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6183 - val_accuracy: 1.0000 - val_loss: 0.6433
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6177 - val_accuracy: 1.0000 - val_loss: 0.6424
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6158 - val_accuracy: 1.0000 - val_loss: 0.6415
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6146 - val_accuracy: 0.7500 - val_loss: 0.6403
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6144 - val_accuracy: 1.0000 - val_loss: 0.6390
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6121 - val_accuracy: 1.0000 - val_loss: 0.6378
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6111 - val_accuracy: 1.0000 - val_loss: 0.6365
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6110 - val_accuracy: 1.0000 - val_loss: 0.6351
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6082 - val_accuracy: 1.0000 - val_loss: 0.6343
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6077 - val_accuracy: 1.0000 - val_loss: 0.6333
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6058 - val_accuracy: 1.0000 - val_loss: 0.6321
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6045 - val_accuracy: 1.0000 - val_loss: 0.6315
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6039 - val_accuracy: 1.0000 - val_loss: 0.6303
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6022 - val_accuracy: 1.0000 - val_loss: 0.6291
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.6012 - val_accuracy: 1.0000 - val_loss: 0.6281
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5995 - val_accuracy: 1.0000 - val_loss: 0.6269
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5989 - val_accuracy: 1.0000 - val_loss: 0.6257
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5971 - val_accuracy: 1.0000 - val_loss: 0.6247
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5957 - val_accuracy: 1.0000 - val_loss: 0.6232
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5944 - val_accuracy: 1.0000 - val_loss: 0.6224
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5934 - val_accuracy: 1.0000 - val_loss: 0.6213
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5920 - val_accuracy: 1.0000 - val_loss: 0.6197
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5910 - val_accuracy: 1.0000 - val_loss: 0.6181
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5895 - val_accuracy: 1.0000 - val_loss: 0.6177
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5882 - val_accuracy: 1.0000 - val_loss: 0.6169
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5866 - val_accuracy: 1.0000 - val_loss: 0.6154
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5857 - val_accuracy: 1.0000 - val_loss: 0.6137
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5842 - val_accuracy: 1.0000 - val_loss: 0.6125
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5826 - val_accuracy: 1.0000 - val_loss: 0.6118
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5814 - val_accuracy: 1.0000 - val_loss: 0.6102
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5801 - val_accuracy: 1.0000 - val_loss: 0.6089
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5790 - val_accuracy: 1.0000 - val_loss: 0.6074
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5778 - val_accuracy: 1.0000 - val_loss: 0.6069
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5762 - val_accuracy: 1.0000 - val_loss: 0.6056
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5747 - val_accuracy: 1.0000 - val_loss: 0.6042
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5737 - val_accuracy: 1.0000 - val_loss: 0.6028
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5730 - val_accuracy: 1.0000 - val_loss: 0.6021
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5707 - val_accuracy: 1.0000 - val_loss: 0.6009
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5693 - val_accuracy: 1.0000 - val_loss: 0.5992
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5682 - val_accuracy: 1.0000 - val_loss: 0.5984
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5666 - val_accuracy: 1.0000 - val_loss: 0.5968
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5653 - val_accuracy: 1.0000 - val_loss: 0.5957
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5639 - val_accuracy: 1.0000 - val_loss: 0.5943
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5624 - val_accuracy: 1.0000 - val_loss: 0.5934
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5612 - val_accuracy: 1.0000 - val_loss: 0.5916
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5596 - val_accuracy: 1.0000 - val_loss: 0.5900
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5586 - val_accuracy: 1.0000 - val_loss: 0.5886
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5577 - val_accuracy: 1.0000 - val_loss: 0.5882
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5554 - val_accuracy: 1.0000 - val_loss: 0.5865
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5540 - val_accuracy: 1.0000 - val_loss: 0.5857
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5527 - val_accuracy: 1.0000 - val_loss: 0.5839
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5515 - val_accuracy: 1.0000 - val_loss: 0.5829
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5499 - val_accuracy: 1.0000 - val_loss: 0.5811
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5483 - val_accuracy: 1.0000 - val_loss: 0.5802
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5471 - val_accuracy: 1.0000 - val_loss: 0.5786
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5456 - val_accuracy: 1.0000 - val_loss: 0.5770
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5443 - val_accuracy: 1.0000 - val_loss: 0.5753
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5427 - val_accuracy: 1.0000 - val_loss: 0.5745
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5413 - val_accuracy: 1.0000 - val_loss: 0.5734
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5399 - val_accuracy: 1.0000 - val_loss: 0.5715
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5386 - val_accuracy: 1.0000 - val_loss: 0.5699
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5368 - val_accuracy: 1.0000 - val_loss: 0.5689
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5355 - val_accuracy: 1.0000 - val_loss: 0.5676
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5341 - val_accuracy: 1.0000 - val_loss: 0.5664
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5331 - val_accuracy: 1.0000 - val_loss: 0.5650
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5321 - val_accuracy: 1.0000 - val_loss: 0.5644
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5298 - val_accuracy: 1.0000 - val_loss: 0.5630
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5284 - val_accuracy: 1.0000 - val_loss: 0.5610
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5274 - val_accuracy: 1.0000 - val_loss: 0.5602
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5254 - val_accuracy: 1.0000 - val_loss: 0.5587
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5239 - val_accuracy: 1.0000 - val_loss: 0.5570
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5229 - val_accuracy: 1.0000 - val_loss: 0.5549
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5216 - val_accuracy: 1.0000 - val_loss: 0.5533
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5194 - val_accuracy: 1.0000 - val_loss: 0.5523
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5188 - val_accuracy: 1.0000 - val_loss: 0.5513
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5167 - val_accuracy: 1.0000 - val_loss: 0.5501
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5154 - val_accuracy: 1.0000 - val_loss: 0.5491
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5139 - val_accuracy: 1.0000 - val_loss: 0.5474
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5128 - val_accuracy: 1.0000 - val_loss: 0.5454
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5109 - val_accuracy: 1.0000 - val_loss: 0.5438
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5096 - val_accuracy: 1.0000 - val_loss: 0.5427
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5089 - val_accuracy: 1.0000 - val_loss: 0.5407
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5066 - val_accuracy: 1.0000 - val_loss: 0.5403
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5051 - val_accuracy: 1.0000 - val_loss: 0.5387
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5036 - val_accuracy: 1.0000 - val_loss: 0.5376
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5025 - val_accuracy: 1.0000 - val_loss: 0.5358
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.5007 - val_accuracy: 1.0000 - val_loss: 0.5344

In [19]:

from tensorflow.keras import optimizers

In [20]:

opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)